name: Build Flutter for Windows

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows executable
        run: flutter build windows

      # Create the folder where we'll stage the release files
      - name: Create release directory
        run: mkdir release

      # Copy the built files from the correct path to our new release folder
      - name: Copy files to release folder
        run: Copy-Item -Path "build/windows/x64/runner/Release/*" -Destination "release" -Recurse

      # Upload the release folder as a downloadable artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: release/
